packages:
  - 'packages/*'

overrides:
  '@types/react': 19.x
  react: ^19.0.0
  react-dom: ^19.0.0

onlyBuiltDependencies:
  - msw

allowBuilds:
  blake-hash: false
  esbuild: true
  msw: true
  protobufjs: false

minimumReleaseAgeExclude:
  - '@vocdoni/proto@1.15.14'
