// Generates testdata/blind-fixture.json, the cross-language anchor for
// src/blind-secp256k1.ts. Every input is pinned, so the output is stable and
// the TypeScript can be asserted byte for byte against what Go produces —
// which is where a flipped endianness or a stripped leading zero would
// otherwise hide until a real vote is rejected on chain.
//
// Not part of any build; this repo has no Go toolchain in CI. To regenerate:
//
//	mkdir /tmp/blindfix && cp blind-fixture.go /tmp/blindfix/main.go && cd /tmp/blindfix
//	go mod init blindfix
//	go get github.com/arnaucube/go-blindsecp256k1 go.vocdoni.io/dvote@main github.com/ethereum/go-ethereum/crypto
//	go run . > .../testdata/blind-fixture.json
package main

import (
	"encoding/hex"
	"encoding/json"
	"fmt"
	"math/big"
	"os"

	blind "github.com/arnaucube/go-blindsecp256k1"
	"go.vocdoni.io/dvote/crypto/saltedkey"
	ethcrypto "github.com/ethereum/go-ethereum/crypto"
)

type fixture struct {
	Comment       string `json:"comment"`
	BlindPrivKey  string `json:"blindPrivKey"`
	BlindPubKey   string `json:"blindPubKey"`
	ProcessID     string `json:"processId"`
	Weight        string `json:"weight"`
	Salt          string `json:"salt"`
	SaltedPubKey  string `json:"saltedPubKey"`
	K             string `json:"k"`
	TokenR        string `json:"tokenR"`
	Bundle        string `json:"bundle"`
	A             string `json:"a"`
	B             string `json:"b"`
	MBlinded      string `json:"mBlinded"`
	SBlind        string `json:"sBlind"`
	SaltedPrivKey string `json:"saltedPrivKey"`
	M             string `json:"m"`
	H             string `json:"h"`
	F             string `json:"f"`
	Signature     string `json:"signature"`
}

func h(b []byte) string { return hex.EncodeToString(b) }

func be32(x *big.Int) string { return h(x.FillBytes(make([]byte, 32))) }

func main() {
	// Deterministic inputs: this is a fixture, not a key.
	d, _ := new(big.Int).SetString("c87509a1c067bbde78beb793e6fa76530b6382a4c0241e5e4a9ec0a0f44dc0d3", 16)
	k, _ := new(big.Int).SetString("7c0ea1a94b4a4d3f8a7f39a9e4e6f0c4e4f2a1b3c5d7e9fa0b1c2d3e4f5a6b7c", 16)
	a, _ := new(big.Int).SetString("9b1e2d3c4b5a69788796a5b4c3d2e1f00f1e2d3c4b5a69788796a5b4c3d2e1f0", 16)
	bb, _ := new(big.Int).SetString("a1b2c3d4e5f60718293a4b5c6d7e8f90a1b2c3d4e5f60718293a4b5c6d7e8f90", 16)

	sk := (*blind.PrivateKey)(d)
	pk := sk.Public()

	processID, _ := hex.DecodeString("0000000000000000000000000000000000000000000000000000000000000001")
	weight := []byte{0x2a} // 42
	salt, err := saltedkey.Salt(processID, weight)
	if err != nil {
		panic(err)
	}
	saltedSk, err := saltedkey.SaltBlindPrivKey(sk, salt)
	if err != nil {
		panic(err)
	}
	saltedPk, err := saltedkey.SaltBlindPubKey(pk, salt)
	if err != nil {
		panic(err)
	}

	R := (&blind.Point{X: blind.G.X, Y: blind.G.Y}).Mul(k)

	bundle, _ := hex.DecodeString("0a20000000000000000000000000000000000000000000000000000000000000000112147c0ea1a94b4a4d3f8a7f39a9e4e6f0c4e4f2a1b31a012a")
	m := new(big.Int).SetBytes(ethcrypto.Keccak256(bundle))

	// Blind, with the random factors pinned to a/bb (mirrors blindsecp256k1.Blind).
	aR := R.Mul(a)
	bG := (&blind.Point{X: blind.G.X, Y: blind.G.Y}).Mul(bb)
	F := aR.Add(bG)
	rx := new(big.Int).Mod(F.X, blind.N)
	ainv := new(big.Int).ModInverse(a, blind.N)
	hh := new(big.Int).SetBytes(ethcrypto.Keccak256(m.Bytes()))
	mBlinded := new(big.Int).Mod(new(big.Int).Mul(new(big.Int).Mul(ainv, rx), hh), blind.N)

	sBlind, err := saltedSk.BlindSign(mBlinded, k)
	if err != nil {
		panic(err)
	}
	sig := blind.Unblind(sBlind, &blind.UserSecretData{A: a, B: bb, F: F})

	if !blind.Verify(m, sig, saltedPk) {
		panic("go-side verify failed")
	}

	f := fixture{
		Comment:      "generated by a throwaway Go program against arnaucube/go-blindsecp256k1 + vocdoni-node/crypto/saltedkey; see blind-secp256k1.test.ts",
		BlindPrivKey: be32(d),
		BlindPubKey:  h(pk.Bytes()),
		ProcessID:    h(processID),
		Weight:       h(weight),
		Salt:         h(salt),
		SaltedPubKey: h(saltedPk.Bytes()),
		K:            be32(k),
		TokenR:       h(R.Bytes()),
		Bundle:       h(bundle),
		A:            be32(a),
		B:            be32(bb),
		MBlinded:     be32(mBlinded),
		SBlind:       be32(sBlind),
		SaltedPrivKey: be32(saltedSk.BigInt()),
		M:            be32(m),
		H:            be32(hh),
		F:            h(F.Bytes()),
		Signature:    h(sig.BytesUncompressed()),
	}
	out, _ := json.MarshalIndent(f, "", "  ")
	fmt.Fprintln(os.Stdout, string(out))
}
